######################################################################
##
## Filename: PLL_TB.udo
## Created on: Sat Jun 08 0:41:42 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
